### PR TITLE
Prefer yarn over npm

### PR DESCRIPTION
**Pull request by rootulp**
## Description

Remove package-lock.json to resolve this warning:

```warn
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

^ observed when running `yarn install`. 

According to [this StackOverflow answer](https://stackoverflow.com/a/44904494), it is possible to keep both `yarn.lock` and `package-lock.json` in this repo if we keep both up-to-date. If we want to preserve both files, we can close this PR and open a new PR with a README instruction to update both lock files when updating dependencies (subject to manual review).

## Testing
1. yarn install
2. yarn run develop 
3. Confirmed that http://localhost:8000/team/ still works

### CODE REVIEW

**Comment by rootulp** [comment]
Tagging @musalbas for review

**Comment by musalbas** [comment]
This will break the CI scripts. What's the advantage of using yarn over npm?

**Comment by rootulp** [comment]
Thanks for flagging, I can update the CI scripts (ex. [here](https://github.com/celestiaorg/celestia.org/blob/main/.github/workflows/dev.yml#L35=)) if we want this. I've observed `yarn install` is usually faster than `npm install` but this isn't a claim yarn makes ([docs](https://yarnpkg.com/getting-started/qa#is-yarn-faster-than-other-package-managers)).

I think it's preferable to use one or the other but not both unless maintainers want to update both lock files when updating dependencies. 

Which do you prefer?
Option A: Use yarn. Delete `package-lock.json`. Update CI scripts to use yarn.
Option B: Use npm. Delete `yarn.lock`
Option C: Use yarn and npm. Add a README instruction to inform maintainers to keep both lock files up to date.

**Comment by musalbas** [comment]
I think we should do option B given we're already using npm

**Pull request closed without merging**
