### PR TITLE
Update resources page

### PR DESCRIPTION
**Pull request by alex-beckett**
- Added in videos for Ismail's Cosmoverse talk, Nick's interview with Big D, and John's interview with CryptoCito
- Added Nick's podcast with Blockcrunch
- Updated images to a few of the videos

Note:
The order of the videos could be changed to favour more recent ones but I've left the order as is.

### CODE REVIEW

**Comment by musalbas** [comment]
Thanks for this. IMO the most recent ones should appear first. Would you be able to change that?

**Comment by musalbas** [comment]
We should also make sure the podcasts and links at the top are updated. I think they get automatically updated based on the IDs: https://github.com/celestiaorg/celestia.org/blob/main/src/datas/resources/resources.js

**Comment by alex-beckett** [comment]
Besides the two most recent blog posts that have automatically been updated at the top, are there any particular resources that you want to use to replace the older video and the other two blog posts?

**Comment by musalbas** [comment]
I think the cryptocito video with John is probably good.

**Comment by alex-beckett** [comment]
John's video has been updated in the top section, plus the video and podcasts sections have had the most recent content placed at the front.

**Pull request merged**
