### PR TITLE
Update CTAs

### PR DESCRIPTION
**Pull request by alex-beckett**
- Update CTA and button link
image

- Update footer box with new header, sub header, CTA, and button link
image

Gatsby link ([here](https://celestiaorgctaupdates.gatsbyjs.io/))

### CODE REVIEW

**Review by YazzyYaz — APPROVED** [review]

**Comment by musalbas** [comment]
We also need to decide what to do with the "join waitlist for developer beta" button soon and what to do with the developer mailing list (maybe just have one mailing list?)

**Comment by alex-beckett** [comment]
As far as I know, Yaz was going to create a single unified mailing list for the newsletter, and another for node operators @YazzyYaz. The options for the button are:

1. Leave the button as-is for now and update it once the mailing list situation has been updated
2. Update the button to link another page (maybe "technology" or "learn modular")

**Comment by musalbas** [comment]
OK, we can leave it for now

**Comment by musalbas** [comment]
Actually since we're already replacing the button for build on developer beta, we might as well replace the other one too.

**Pull request merged**
