### PR TITLE
Add new terms to the glossary

### PR DESCRIPTION
**Pull request by alex-beckett**
The following terms where added
- [Throughput](https://celestiaorgglossaryadd.gatsbyjs.io/glossary/throughput)
- [Fee market](https://celestiaorgglossaryadd.gatsbyjs.io/glossary/fee-market)
- [slashing](https://celestiaorgglossaryadd.gatsbyjs.io/glossary/slashing)
- [block producer](https://celestiaorgglossaryadd.gatsbyjs.io/glossary/block-producer)
- [validator](https://celestiaorgglossaryadd.gatsbyjs.io/glossary/validator)
- [validator set](https://celestiaorgglossaryadd.gatsbyjs.io/glossary/validator-set)
- [block space](https://celestiaorgglossaryadd.gatsbyjs.io/glossary/block-space)
- [block header](https://celestiaorgglossaryadd.gatsbyjs.io/glossary/block-header)
- [peer to peer network](https://celestiaorgglossaryadd.gatsbyjs.io/glossary/peer-to-peer-network)

### CODE REVIEW

**Comment by musalbas** [comment]
"A measurement of the computational capacity of a blockchain, commonly calculated by the number of transactions that can be processed per second (TPS). However, TPS is a subjective measure of throughput as transactions can vary in size. An objective measurement of throughput is the number of computational units that can be performed per second.

For example, consider a blockchain that has a limit of 15M computational units per block with a block time of 10 seconds. The objective throughput of the blockchain would be 1.5M units per second. Additionally, throughput can also be used to measure other parameters of a blockchain, such as data capacity."

I'm not sure about this. We measure throughput in terms of bytes, not computation. Maybe this is only a definition of "transaction throughput"? I think this definition needs to be tightened up.

Also relevant to "block space":

"The capacity of each block. The amount of block space a blockchain has determines its throughput - how many transactions it can process at a given time. Blockchains that suffer from high fees occur because demand for block space exceeds supply."

**Comment by musalbas** [comment]
"The header of a block that contains a list of relevant metadata. This typically includes a Merkle root of the transactions in the block body, the hash of the previous block, the block height, and the timestamp, among others. The contents of the block header will also vary by sybil mechanism (PoW or PoS) and by the specifications of the individual blockchain."

"sybil mechanism" -> "sybil resistance mechanism"

**Comment by alex-beckett** [comment]
Yes, there should be an example and explanation of data throughput  on the throughput page, but transaction throughput shouldn't be removed because it is still relevant to the general term throughput - unless the terms are separated, one for "transaction throughput" and another for "data throughput"?

**Comment by musalbas** [comment]
Not sure what the best approach is but let me know what your new proposal is and I can sanity check it.

**Comment by alex-beckett** [comment]
What we can do is have
- One term for throughput
- Two separate terms, one for data throughput and another for transaction throughput
- Have all three (_I prefer this_)

**Throughput**
A measurement of the capacity of a blockchain. Throughput primarily measures two elements: data throughput and transaction throughput. Data throughput determines a blockchain’s data capacity, which is measured in kb/s or mb/s. Data throughput is most relevant to data availability layers because their primary job is to provide a high capacity for data.

Transaction throughput measures the computational capacity of a blockchain, which is commonly calculated by the number of transactions that can be processed per second (TPS). However, TPS is a subjective measure of throughput as transactions can vary in size. An objective measurement of throughput is the number of computational units that can be performed per second.

**Transaction throughput**
The computational capacity of a blockchain. Transaction throughput is commonly calculated by the number of transactions that can be processed per second (TPS). However, TPS is a subjective measure of throughput as transactions can vary in size. Therefore, larger transactions will result in lower TPS, and smaller transactions will lead to higher TPS. An objective measurement of throughput is the number of computational units that can be performed per second.

For example, consider a blockchain that has a limit of 15M computational units per block with a block time of 10 seconds. The objective throughput of the blockchain would be 1.5M units per second. Additionally, throughput can also be used to measure other parameters of a blockchain, such as data capacity.

**Data throughput**
A measurement of the data capacity of a blockchain. Data throughput is calculated by the amount of data that a blockchain can process, measured in kb/s or mb/s. For example, consider a blockchain that has a block size of 10MB and a block time of 20 seconds. The data throughput of the blockchain would be 0.5MB/s. Data throughput is most relevant to data availability layers because their primary job is to provide a high capacity for data.

**Comment by musalbas** [comment]
This seems reasonable to me.

**Comment by musalbas** [comment]
Not sure what the best approach is but let me know what your new proposal 
is and I can sanity check it.

**Pull request merged**
